services:
  # app:
  #   container_name: app
  #   build:
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./src:/usr/src/app/src
  #     - ./public:/usr/src/app/public
  #     - ./prisma:/usr/src/app/prisma
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - pg-db
  pg-db:
    image: postgres:15.2-alpine
    container_name: pg-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      PGPASSWORD: ${DB_PASS?}
      POSTGRES_USER: ${DB_USER?}
      POSTGRES_PASSWORD: ${DB_PASS?}
      POSTGRES_DB: ${DB_NAME?}
    volumes:
      - pg-db-data:/var/lib/postgresql/data
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio
    restart: unless-stopped
    ports:
      - ${PRISMA_STUDIO_PORT}:5555
  pg-admin:
    container_name: pg-admin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
volumes:
  pg-db-data:
    driver: local
