services:
  frontend:
    container_name: frontend-app
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    ports:
      - '3000:3000'
