import { getLayout } from '@/layouts/MainLayout'

export default function Home() {
  return (
    <>
      <title>V-DOC</title>
      <link rel="icon" href="/favicon.ico" />
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.png" />
      <h1>Hello there from main page!</h1>
    </>
  )
}

Home.getLayout = getLayout
